// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_geo_locate
DataFrame cpp_geo_locate(CharacterVector cn_strings, std::vector<std::string> prov_dd_strings, std::vector<int> prov_dd_codes, std::vector<std::string> city_dd_strings, std::vector<int> city_dd_codes, std::vector<std::string> cnty_dd_strings, std::vector<int> cnty_dd_codes, std::vector<std::string> cnty_dd_strings_2015, std::vector<int> cnty_dd_codes_2015);
RcppExport SEXP _geolocChina_cpp_geo_locate(SEXP cn_stringsSEXP, SEXP prov_dd_stringsSEXP, SEXP prov_dd_codesSEXP, SEXP city_dd_stringsSEXP, SEXP city_dd_codesSEXP, SEXP cnty_dd_stringsSEXP, SEXP cnty_dd_codesSEXP, SEXP cnty_dd_strings_2015SEXP, SEXP cnty_dd_codes_2015SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type cn_strings(cn_stringsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type prov_dd_strings(prov_dd_stringsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type prov_dd_codes(prov_dd_codesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type city_dd_strings(city_dd_stringsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type city_dd_codes(city_dd_codesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type cnty_dd_strings(cnty_dd_stringsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type cnty_dd_codes(cnty_dd_codesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type cnty_dd_strings_2015(cnty_dd_strings_2015SEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type cnty_dd_codes_2015(cnty_dd_codes_2015SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_geo_locate(cn_strings, prov_dd_strings, prov_dd_codes, city_dd_strings, city_dd_codes, cnty_dd_strings, cnty_dd_codes, cnty_dd_strings_2015, cnty_dd_codes_2015));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geolocChina_cpp_geo_locate", (DL_FUNC) &_geolocChina_cpp_geo_locate, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_geolocChina(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
