// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_geo_locate
DataFrame cpp_geo_locate(const CharacterVector& cn_strings, const Environment& cn_env);
RcppExport SEXP _geolocChina_cpp_geo_locate(SEXP cn_stringsSEXP, SEXP cn_envSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type cn_strings(cn_stringsSEXP);
    Rcpp::traits::input_parameter< const Environment& >::type cn_env(cn_envSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_geo_locate(cn_strings, cn_env));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geolocChina_cpp_geo_locate", (DL_FUNC) &_geolocChina_cpp_geo_locate, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_geolocChina(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
