# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_geo_locate <- function(cn_strings) {
    .Call(`_geolocChina_cpp_geo_locate`, cn_strings)
}

